import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    navCars: "CARS",
    navFavorites: "FAVORITES",
    navContact: "CONTACT",
    navAdmin: "ADMIN",
    login: "Log in",
    register: "Sign up",
    logout: "Log out",
    loginTitle: "Welcome back",
    loginText: "Log in to access your DriveHub account.",
    registerTitle: "Create your account",
    registerText: "Join DriveHub and keep everything about your cars in one place.",
    username: "Username",
    password: "Password",
    confirmPassword: "Confirm password",
    profileImage: "Profile image",
    profileImageHint: "Optional. JPG, PNG or WebP recommended.",
    passwordMin: "Password must be at least 6 characters",
    passwordMismatch: "Passwords do not match",
    usernameMin: "Username must be at least 2 characters",
    loggingIn: "Logging in...",
    registering: "Creating account...",
    createAccount: "Create account",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    adminEyebrow: "Administration",
    adminTitle: "Dashboard",
    adminWelcome: "Welcome, {{username}}. This area is ready for future management tools.",
    adminSummary: "Administration summary",
    adminAccount: "Account",
    adminAccess: "Access level",
    adminRole: "Administrator",
    adminStatus: "System status",
    adminReady: "Ready",

    adminInventoryTitle: "Car inventory",
    adminInventoryText: "Review the vehicles currently registered in DriveHub.",
    adminInventoryOpen: "Open inventory",
    adminBack: "Back to dashboard",
    adminCarsEyebrow: "Inventory",
    adminCarsTitle: "Cars",
    adminCarsText: "Review all vehicle details and their current availability.",
    adminNewCar: "New car",
    adminCarsBack: "Back to inventory",
    carNewTitle: "Add a car",
    carNewText: "Enter the vehicle information and add its gallery images.",
    carBasicData: "Vehicle details",
    carBasicDataText: "Complete the main inventory information.",
    carNotes: "Notes",
    carNotesPlaceholder: "Condition, maintenance, equipment...",
    carImages: "Images",
    carImagesText: "The first selected image will be used as the cover.",
    carImagesSelect: "Select images",
    carImagesHint: "Up to 10 images",
    carImagesMax: "You can select up to 10 images",
    carYearInvalid: "Enter a valid year",
    carNumberInvalid: "Enter a number greater than or equal to zero",
    carPriceInvalid: "Price must be greater than zero",
    carCreate: "Create car",
    carCreating: "Creating car...",
    carCreateSuccess: "Car created successfully. Returning to inventory...",
    cancel: "Cancel",
    adminCarsLoading: "Loading inventory...",
    adminCarsErrorTitle: "Inventory unavailable",
    adminCarsErrorText: "Cars could not be loaded. Please try again later.",
    adminCarsEmptyTitle: "No cars in inventory",
    adminCarsEmptyText: "Registered vehicles will appear here.",
    adminCarsCount: "cars registered",
    carCover: "Cover",
    carBrand: "Brand",
    carModel: "Model",
    carYear: "Year",
    carMileage: "Mileage",
    carPrice: "Price",
    carFuel: "Fuel",
    carTransmission: "Transmission",
    carStatus: "Status",
    carFuelGasoline: "Gasoline",
    carFuelDiesel: "Diesel",
    carFuelHybrid: "Hybrid",
    carFuelElectric: "Electric",
    carFuelLpg: "LPG",
    carTransmissionManual: "Manual",
    carTransmissionAutomatic: "Automatic",
    carStatusAvailable: "Available",
    carStatusReserved: "Reserved",
    carStatusSold: "Sold",

    heroEyebrow: "Premium used cars",
    heroTitle: "Drive what you love",
    heroText:
      "Handpicked performance and sport cars. Transparent details. Real drivers.",

    searchBrand: "Brand",
    allBrands: "All brands",

    searchMaxPrice: "Max price",
    anyPrice: "Any price",

    searchYear: "Year",
    anyYear: "Any year",

    searchCars: "Search cars",

    verifiedCars: "Verified cars",
    verifiedCarsText: "Checked and inspected",

    noHiddenFees: "No hidden fees",
    noHiddenFeesText: "What you see is what you pay",

    personalSupport: "Personal support",
    personalSupportText: "We're here to help",

    featured: "Featured",
    viewDetails: "View details",

    recentlyAdded: "Recently added",
    viewAllCars: "View all cars",
    contactEyebrow: "Contact",
    contactTitle: "Let’s talk about your next car",
    contactText:
      "Send us a message and we will help you with buying, selling or finding the right vehicle.",
    contactPhone: "Phone",
    contactLocation: "Location",
    contactBoxTitle: "Personal support",
    contactBoxText:
      "We review every request and guide you through the process with clear information and no pressure.",
    formName: "Name",
    formNamePlaceholder: "Your name",
    formEmail: "Email",
    formSubject: "Subject",
    formSubjectPlaceholder: "Choose an option",
    formSubjectBuy: "I want to buy a car",
    formSubjectSell: "I want to sell my car",
    formSubjectSupport: "I need support",
    formMessage: "Message",
    formMessagePlaceholder: "Tell us what you need...",
    formSubmit: "Send message",
    formRequired: "This field is required",
    formNameMin: "Name must be at least 2 characters",
    formEmailInvalid: "Enter a valid email",
    formMessageMin: "Message must be at least 10 characters",
    formSuccess: "Message sent successfully. We will contact you soon.",
    detailBack: "Back to cars",
    detailAvailable: "Available now",
    detailSelectedVehicle: "Selected vehicle",
    detailYear: "Year",
    detailMileage: "Mileage",
    detailDescription: "Description",
    detailDescriptionText:
      "This vehicle is part of our selected inventory. It includes clear basic information, mileage and relevant notes provided by the seller.",
    detailContactSeller: "Contact seller",
    detailAddFavorites: "Add to favorites",
    detailLoading: "Loading car...",
    detailNotFound: "Car not found.",
    loadingCars: "Loading cars...",
    loadingCar: "Loading car...",
    favoritesEyebrow: "Favorites",
    favoritesTitle: "Your saved cars",
    favoritesText:
      "Keep track of the cars you like and come back to them whenever you want.",
    favoritesEmptyTitle: "No favorite cars yet",
    favoritesEmptyText:
      "Start exploring the catalog and save the cars that catch your attention.",
    searchMileage: "Mileage",
    anyMileage: "Any mileage",
    clearFilters: "Clear filters",
    resultsFound: "results found",
    noResultsTitle: "No cars found",
    noResultsText:
      "Try changing your filters to discover more available vehicles.",
    footerText: "Browse selected vehicles and find the right car for you.",

    footerNavigation: "Navigation",

    footerResources: "Resources",

    footerRights: "All rights reserved.",
  },

  es: {
    navCars: "COCHES",
    navFavorites: "FAVORITOS",
    navContact: "CONTACTO",
    navAdmin: "ADMIN",
    login: "Iniciar sesión",
    register: "Registrarse",
    logout: "Cerrar sesión",
    loginTitle: "Bienvenido de nuevo",
    loginText: "Inicia sesión para acceder a tu cuenta de DriveHub.",
    registerTitle: "Crea tu cuenta",
    registerText: "Únete a DriveHub y ten todo lo relacionado con tus coches en un solo lugar.",
    username: "Nombre de usuario",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    profileImage: "Imagen de perfil",
    profileImageHint: "Opcional. Se recomienda JPG, PNG o WebP.",
    passwordMin: "La contraseña debe tener al menos 6 caracteres",
    passwordMismatch: "Las contraseñas no coinciden",
    usernameMin: "El usuario debe tener al menos 2 caracteres",
    loggingIn: "Iniciando sesión...",
    registering: "Creando cuenta...",
    createAccount: "Crear cuenta",
    noAccount: "¿No tienes una cuenta?",
    hasAccount: "¿Ya tienes una cuenta?",
    adminEyebrow: "Administración",
    adminTitle: "Panel de control",
    adminWelcome: "Bienvenido, {{username}}. Esta área está preparada para futuras herramientas de gestión.",
    adminSummary: "Resumen de administración",
    adminAccount: "Cuenta",
    adminAccess: "Nivel de acceso",
    adminRole: "Administrador",
    adminStatus: "Estado del sistema",
    adminReady: "Preparado",

    adminInventoryTitle: "Inventario de coches",
    adminInventoryText: "Consulta los vehículos registrados actualmente en DriveHub.",
    adminInventoryOpen: "Abrir inventario",
    adminBack: "Volver al panel",
    adminCarsEyebrow: "Inventario",
    adminCarsTitle: "Coches",
    adminCarsText: "Consulta los datos de todos los vehículos y su disponibilidad actual.",
    adminNewCar: "Nuevo coche",
    adminCarsBack: "Volver al inventario",
    carNewTitle: "Añadir coche",
    carNewText: "Introduce la información del vehículo y añade las imágenes de su galería.",
    carBasicData: "Datos del vehículo",
    carBasicDataText: "Completa la información principal del inventario.",
    carNotes: "Notas",
    carNotesPlaceholder: "Estado, mantenimiento, equipamiento...",
    carImages: "Imágenes",
    carImagesText: "La primera imagen seleccionada se utilizará como portada.",
    carImagesSelect: "Seleccionar imágenes",
    carImagesHint: "Hasta 10 imágenes",
    carImagesMax: "Puedes seleccionar hasta 10 imágenes",
    carYearInvalid: "Introduce un año válido",
    carNumberInvalid: "Introduce un número mayor o igual que cero",
    carPriceInvalid: "El precio debe ser mayor que cero",
    carCreate: "Crear coche",
    carCreating: "Creando coche...",
    carCreateSuccess: "Coche creado correctamente. Volviendo al inventario...",
    cancel: "Cancelar",
    adminCarsLoading: "Cargando inventario...",
    adminCarsErrorTitle: "Inventario no disponible",
    adminCarsErrorText: "No se pudieron cargar los coches. Inténtalo de nuevo más tarde.",
    adminCarsEmptyTitle: "No hay coches en el inventario",
    adminCarsEmptyText: "Los vehículos registrados aparecerán aquí.",
    adminCarsCount: "coches registrados",
    carCover: "Portada",
    carBrand: "Marca",
    carModel: "Modelo",
    carYear: "Año",
    carMileage: "Kilómetros",
    carPrice: "Precio",
    carFuel: "Combustible",
    carTransmission: "Transmisión",
    carStatus: "Estado",
    carFuelGasoline: "Gasolina",
    carFuelDiesel: "Diésel",
    carFuelHybrid: "Híbrido",
    carFuelElectric: "Eléctrico",
    carFuelLpg: "GLP",
    carTransmissionManual: "Manual",
    carTransmissionAutomatic: "Automática",
    carStatusAvailable: "Disponible",
    carStatusReserved: "Reservado",
    carStatusSold: "Vendido",

    heroEyebrow: "Coches premium de ocasión",
    heroTitle: "Conduce lo que te apasiona",
    heroText:
      "Una selección de deportivos y vehículos de altas prestaciones con total transparencia.",

    searchBrand: "Marca",
    allBrands: "Todas las marcas",

    searchMaxPrice: "Precio máximo",
    anyPrice: "Cualquier precio",

    searchYear: "Año",
    anyYear: "Cualquier año",

    searchCars: "Buscar coches",

    verifiedCars: "Coches verificados",
    verifiedCarsText: "Inspeccionados y revisados",

    noHiddenFees: "Sin costes ocultos",
    noHiddenFeesText: "El precio es el precio",

    personalSupport: "Asesoramiento",
    personalSupportText: "Te acompañamos durante la compra",

    featured: "Destacado",
    viewDetails: "Ver detalles",

    recentlyAdded: "Últimos vehículos",
    viewAllCars: "Ver todos",
    contactEyebrow: "Contacto",
    contactTitle: "Hablemos de tu próximo coche",
    contactText:
      "Envíanos un mensaje y te ayudaremos a comprar, vender o encontrar el vehículo adecuado.",
    contactPhone: "Teléfono",
    contactLocation: "Ubicación",
    contactBoxTitle: "Asesoramiento personal",
    contactBoxText:
      "Revisamos cada solicitud y te guiamos durante el proceso con información clara y sin presión.",
    formName: "Nombre",
    formNamePlaceholder: "Tu nombre",
    formEmail: "Email",
    formSubject: "Asunto",
    formSubjectPlaceholder: "Elige una opción",
    formSubjectBuy: "Quiero comprar un coche",
    formSubjectSell: "Quiero vender mi coche",
    formSubjectSupport: "Necesito ayuda",
    formMessage: "Mensaje",
    formMessagePlaceholder: "Cuéntanos qué necesitas...",
    formSubmit: "Enviar mensaje",
    formRequired: "Este campo es obligatorio",
    formNameMin: "El nombre debe tener al menos 2 caracteres",
    formEmailInvalid: "Introduce un email válido",
    formMessageMin: "El mensaje debe tener al menos 10 caracteres",
    formSuccess: "Mensaje enviado correctamente. Contactaremos contigo pronto.",
    detailBack: "Volver a coches",
    detailAvailable: "Disponible ahora",
    detailSelectedVehicle: "Vehículo seleccionado",
    detailYear: "Año",
    detailMileage: "Kilometraje",
    detailDescription: "Descripción",
    detailDescriptionText:
      "Este vehículo forma parte de nuestro catálogo seleccionado. Incluye información básica clara, kilometraje y notas relevantes aportadas por el vendedor.",
    detailContactSeller: "Contactar con el vendedor",
    detailAddFavorites: "Añadir a favoritos",
    detailLoading: "Cargando coche...",
    detailNotFound: "Coche no encontrado.",
    loadingCars: "Cargando vehículos...",
    loadingCar: "Cargando vehículo...",
    favoritesEyebrow: "Favoritos",
    favoritesTitle: "Tus coches guardados",
    favoritesText:
      "Guarda los coches que te interesan y vuelve a ellos cuando quieras.",
    favoritesEmptyTitle: "Aún no tienes coches favoritos",
    favoritesEmptyText:
      "Explora el catálogo y guarda los vehículos que te llamen la atención.",
    searchMileage: "Kilometraje",
    anyMileage: "Cualquier kilometraje",
    clearFilters: "Limpiar filtros",
    resultsFound: "resultados encontrados",
    noResultsTitle: "No se encontraron coches",
    noResultsText:
      "Prueba a cambiar los filtros para descubrir más vehículos disponibles.",
    footerText:
      "Explora vehículos seleccionados y encuentra el coche adecuado para ti.",

    footerNavigation: "Navegación",

    footerResources: "Recursos",

    footerRights: "Todos los derechos reservados.",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem("drivehub-lang") || "en",
  );

  const changeLanguage = (code) => {
    setLanguage(code);
    localStorage.setItem("drivehub-lang", code);
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        changeLanguage,
        t: translations[language],
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
